/**
 * Background manager controls the non interactive background objects
 */

export enum PirateTile {
    BottomLeftCornerSand = 1,
    BottomLeftEdgeSand = 2,
    BottomMiddleEdgeSand = 3,
    BottomRightCornerSand = 4,
    BottomRightEdgeSand = 5,

    CenterCenterGravelSand = 6,
    CenterCenterPlainSand = 7,
    CenterCenterDotsSand = 8,

    Rock = 9,
    PlantA = 10,
    PlantB = 11,

    SideLeftEdgeSand = 12,
    SideRightEdgeSand = 13,
    TopLeftCornerSand = 14,
    TopLeftSideSand = 15,
    TopMiddleEdgeSand = 16,
    TopRightCornerSand = 17,
    TopRightSideSand = 18,

    Water = 19,
}

export class BackgroundManager {
    /**
     * Adds the parallax background to the scene
     */
    constructor(scene: Phaser.Scene) {
        const tileSize = 128;
        const mapWidth = 20;
        const mapHeight = 10;
        const map = scene.make.tilemap({
            tileWidth: tileSize,
            tileHeight: tileSize,
            width: mapWidth,
            height: mapHeight,
        });
        const tileset = map.addTilesetImage("background", "background", tileSize, tileSize, 0, 4, 1);
        const water = map.createBlankLayer("water", tileset);
        const island = map.createBlankLayer("island", tileset);
        const objects = map.createBlankLayer("objects", tileset);

        const islandData = [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.CenterCenterDotsSand,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            0,
            0,
            0,
            0,
            0,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterPlainSand,
            PirateTile.CenterCenterGravelSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterGravelSand,
            PirateTile.CenterCenterDotsSand,
            0,
            0,
            0,
            0,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterPlainSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            0,
            0,
            0,
            0,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterGravelSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            0,
            0,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterPlainSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterGravelSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            0,
            0,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterGravelSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            0,
            0,
            0,
            0,
            0,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterDotsSand,
            PirateTile.CenterCenterGravelSand,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ];

        const objectData = [
            PirateTile.Rock,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.PlantB,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.Rock,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.PlantA,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.Rock,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.PlantA,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ];

        water.fill(PirateTile.Water, 0, 0, mapWidth, mapHeight);
        for (let i = 0; i < islandData.length; i++) {
            island.putTileAt(islandData[i], Math.floor(i / mapHeight), i % mapHeight);
        }
        for (let i = 0; i < objectData.length; i++) {
            objects.putTileAt(objectData[i], Math.floor(i / mapHeight), i % mapHeight);
        }

        // temp
        scene.cameras.main.setBounds(0, 0, map.widthInPixels, map.heightInPixels);
    }
}
