/**
 * Background manager controls the non interactive background objects
 */

 export enum PirateTile {
    IslandA = 6,
    DarkIsland = 7,
    LightIsland = 8,

    Rock = 9,
    PlantA = 10,
    PlantB = 11
 }

export class BackgroundManager {
    /**
     * Adds the parallax background to the scene
     */
    constructor(scene: Phaser.Scene) {
        const tileSize = 128;
        const mapSize = 10;
        const map = scene.make.tilemap({ tileWidth: tileSize, tileHeight: tileSize, width: mapSize, height: mapSize });
        const tileset = map.addTilesetImage("background", "background", tileSize, tileSize, 0, 4, 1);
        const water = map.createBlankLayer("water", tileset);
        const island = map.createBlankLayer("island", tileset);
        const objects = map.createBlankLayer("objects", tileset);

        const islandData = [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.LightIsland,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            0,
            0,
            0,
            0,
            0,
            PirateTile.LightIsland,
            PirateTile.DarkIsland,
            PirateTile.IslandA,
            PirateTile.LightIsland,
            PirateTile.IslandA,
            PirateTile.LightIsland,
            0,
            0,
            0,
            0,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.DarkIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            0,
            0,
            0,
            0,
            PirateTile.LightIsland,
            PirateTile.IslandA,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            0,
            0,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.DarkIsland,
            PirateTile.LightIsland,
            PirateTile.IslandA,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            0,
            0,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.IslandA,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            0,
            0,
            0,
            0,
            0,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.LightIsland,
            PirateTile.IslandA,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ];

        const objectData = [
            PirateTile.Rock,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.PlantB,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.Rock,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.PlantA,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.Rock,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            PirateTile.PlantA,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ];

        water.fill(19, 0, 0, mapSize, mapSize);
        for (let i = 0; i < islandData.length; i++) {
            island.putTileAt(islandData[i], Math.floor(i / mapSize), i % mapSize);
        }
        for (let i = 0; i < objectData.length; i++) {
            objects.putTileAt(objectData[i], Math.floor(i / mapSize), i % mapSize);
        }

        // temp
        scene.cameras.main.setBounds(0, 0, map.widthInPixels, map.heightInPixels);
    }
}
