/**
 * Background manager controls the non interactive background objects
 */
export class BackgroundManager {
    /**
     * Adds the parallax background to the scene
     */
    constructor(scene: Phaser.Scene) {
        const tileSize = 128;
        const mapSize = 10;
        const map = scene.make.tilemap({ tileWidth: tileSize, tileHeight: tileSize, width: mapSize, height: mapSize });
        const tileset = map.addTilesetImage("background", "background", tileSize, tileSize, 0, 4, 1);
        const water = map.createBlankLayer("water", tileset);
        const island = map.createBlankLayer("island", tileset);
        const objects = map.createBlankLayer("objects", tileset);

        const islandData = [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            8,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            8,
            8,
            8,
            8,
            8,
            0,
            0,
            0,
            0,
            0,
            8,
            7,
            6,
            8,
            6,
            8,
            0,
            0,
            0,
            0,
            8,
            8,
            8,
            7,
            8,
            8,
            0,
            0,
            0,
            0,
            8,
            6,
            8,
            8,
            8,
            8,
            8,
            0,
            0,
            8,
            8,
            8,
            7,
            8,
            6,
            8,
            8,
            0,
            0,
            8,
            8,
            8,
            6,
            8,
            8,
            8,
            0,
            0,
            0,
            0,
            0,
            8,
            8,
            8,
            6,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ];

        const objectData = [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            11,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            9,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            10,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            9,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            10,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
        ];

        water.fill(19, 0, 0, mapSize, mapSize);
        for (let i = 0; i < islandData.length; i++) {
            island.putTileAt(islandData[i], Math.floor(i / mapSize), i % mapSize);
        }
        for (let i = 0; i < objectData.length; i++) {
            objects.putTileAt(objectData[i], Math.floor(i / mapSize), i % mapSize);
        }

        // temp
        scene.cameras.main.setBounds(0, 0, map.widthInPixels, map.heightInPixels);
    }
}
